title: Steve Geall
description: > # this means to ignore newlines until "baseurl:"
  Awesome description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://borough11.co.nz" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Steve Geall. # add your name
author-img: steve-geall.jpg # add your photo
about-author: Creating the technical vision and developing solutions to business problems # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: borough11 # add your Github handle
social-linkedin: steve-geall-b0044657 # add your Linkedin handle
social-email: stevegeall@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
